import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Cards from './components/Cards';

import React, { useState, Component } from "react";

import Link from 'next/link'



class  Home extends Component {

  constructor(props) {
    super(props);
    this.state = {
      special: ''
    };
  }


  componentDidMount () {

    console.log('mount')
    
    var specialisation = localStorage.getItem('specialisation');
    var data = {}
    if (specialisation === null) {
      data = {developer: 0, nature: 0}
    } else {
      data = JSON.parse(specialisation);
    }

    console.log(data)

    var dataCount = data.nature + data.developer;

    if ( dataCount !== 0 ) {
      var count = 0; 
      var special = '';
      Object.keys(data).forEach(function(key) {
        console.log( data[key]  )
        
        if (data[key] > count) {
          special = key;
          count = data[key];
        }
        else if (data[key] == count) {
          special = special + ',' + key;
        }


      })

      if (count > 0) {
          console.log(special)

          this.setState({
            special
          });       
      }


    }
    
 
  }

  

  render (){
    
    return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Specialisation Component
        </h1>

        <Cards special={this.state.special} />

        <div className={styles.grid}>
          <Link href="/developer" className={styles.card}>
            <h2 className="link">Developer &rarr;</h2>
          </Link>
          <Link href="/marketing" className={styles.card}>
            <h2 className="link">Marketing &rarr;</h2>
          </Link>

          <Link href="/reset" className={styles.card}>
            <h2 className="link">Reset &rarr;</h2>
          </Link>


        </div>



      </main>


    </div>
  )



}
}


export default Home;