import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


import React, { Component } from "react";

import Link from 'next/link'

class  Developer extends Component {

  constructor(props) {
    super(props);
    this.state = {
      specialisation: ''
    };
  }

  componentDidMount () {
    var specialisation = localStorage.getItem('specialisation');
    var specialisationJSON = {}
    if (specialisation === null) {
      specialisationJSON = {developer: 0, marketing: 0}
    } else {
      specialisationJSON = JSON.parse(specialisation);
    }
    specialisationJSON.marketing += 10;
    localStorage.setItem('specialisation', JSON.stringify(specialisationJSON) );
    this.setState({
      specialisation: JSON.stringify(specialisationJSON) 
    });
  }

  render() {
        return (<div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
            <h1 className={styles.title}>
            Marketing Page
            </h1>
            <h3>Marketing specialisation been given +10 points.</h3>
            <pre>
            {this.state.specialisation}
            </pre>

            <Link href="/" className={styles.card}>
            <h2 className="link">&larr; Homepage</h2>
          </Link>

          </main>


        </div>
      )
  }


}


export default Developer;